name: 提取Lede1806-config
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: aarch64/Lede1806/feeds.conf.default
  CONFIG_FILE: aarch64/Lede1806/1806SSHCONFIG.config
  DIY_P1_SH: aarch64/Lede1806/1806diy-part1.sh
  DIY_P2_SH: aarch64/Lede1806/1806diy-part2.sh
  SSH_ACTIONS: true
  UPLOAD_CONFIG: true
  DELETE_ARTIFACTS: true   # 删除旧的工作流程运行和工件
  TZ: Asia/Shanghai
  FILE_NAME: config
  PRODUCT_NAME: Build_config

jobs:
  build:
    runs-on: ubuntu-22.04
    #if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    name: 提取Lede1806-config
    strategy:
      fail-fast: false
      
    steps:
    - name: 准备
      uses: actions/checkout@master

    - name: 部署编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt -y purge azure-cli* docker* ghc* zulu* firefox google* dotnet* powershell* openjdk* mysql* mongodb* dotnet* snap* aspnetcore*
        [ -n "$AGENT_TOOLSDIRECTORY" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo -E apt update
        # 添加 subversion 安装
        sudo -E apt -y install $(curl -fsSL https://is.gd/depends_ubuntu_2204) subversion clang llvm
        sudo -E apt -y autoremove --purge
        sudo -E systemctl daemon-reload
        sudo -E apt clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        echo "status=success" >> $GITHUB_OUTPUT
        df -Th

    - name: 下载源码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H")
        echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "DATE1=$(date "+%Y.%m.%d.%H%M")" >> $GITHUB_ENV

    - name: 加载自定义配置
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: 更新软件包
      run: cd openwrt && ./scripts/feeds update -a

    - name: 安装软件包
      run: cd openwrt && ./scripts/feeds install -a

    - name: 加载自定义配置
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH
        sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate
        sed -i 's/OpenWrt/MRG AutoBuild ${{ env.DATE1 }} @ OpenWrt/g' package/lean/default-settings/files/zzz-default-settings
        
    - name: SSH远程连接（配置固件）
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: 生成.config配置文件
      run: |
        cd openwrt
        make defconfig
        ./scripts/diffconfig.sh > ${GITHUB_WORKSPACE}/config.txt
    
    - name: 上传.config配置文件
      uses: actions/upload-artifact@v4
      if: env.UPLOAD_CONFIG == 'true'
      with:
        name: ${{ env.FILE_NAME }}-${{ env.DATE1 }}-
        path: config.txt
        
    - name: 检查空间使用情况
      if: (!cancelled())
      run: df -hT

    - name: 删除旧的工作流程运行和工件
      uses: Mattraks/delete-workflow-runs@main
      if: env.DELETE_ARTIFACTS == 'true'
      with:
        token: ${{ secrets.RELEASES_TOKEN }}    # 令牌
        repository: ${{ github.repository }}    # 运行工作流的存储库的名称。
        retain_days: 1                          # 工作流的保留天数进行比较的天数       
        keep_minimum_runs: 0                    # 工作流程保留的最少运行次数
        
#    - name: 取消编译
#      uses: potiuk/cancel-workflow-runs@master
#      with:
#        cancelMode: self
#        notifyPRCancel: true
#        token: ${{ secrets.RELEASES_TOKEN }}
